### ISSUE TITLE
eg.API.storage.download is not a function

### ISSUE THREAD

**Issue by jacobscarter** [egnyte/egnyte-js-sdk#4]
@naugtur 

When using your example filepicker_usecase.html as well as trying to implement it in my own project I get the error message:

`Uncaught TypeError: eg.API.storage.download is not a function`

Can you verify this is working for you or suggest debugging options to discover why I am getting this error.

Thanks.

**Comment by naugtur** [comment]
Hi,

In short: `API.storage.fileId("6a5ec46a5e4c6e4c65e4c654e6").download` is a function.

As per docs, the function is at API.storage.*identify(...)*.download where `identify()` is one of:
- `path("/Shared/...")` - if you want to identify the resource by path
- `fileId("...")` - if you want to identify a file by id

 `folderId` is also there, but doesn't seem relevant to your case.

Documented here: https://github.com/egnyte/egnyte-js-sdk/blob/master/src/docs/api.md#identification

**Comment by jacobscarter** [comment]
I would then suggest editing your example page so that it has working code on it.  Thanks for pointing me in the right direction.

**Comment by naugtur** [comment]
Thanks for letting me know about this. Appreciated.
